extensions:
  zpages:
    endpoint: localhost:55679
  pprof:
    endpoint: :1888

receivers:
  kafka:
    brokers:
      - ${env:KAFKA_HOST}:9092
    logs:
      topic: otlp_logs_coll
    traces:
      topic: otlp_traces_coll
    metrics:
      topic: otlp_spans_coll

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  clickhouse:
    endpoint: http://${env:CLICKHOUSE_HOST}:8123?enable_json_type=1
    database: otel

service:
  pipelines:
    traces:
      receivers: [kafka]
      processors: [batch]
      exporters: [clickhouse]

    logs:
      receivers: [kafka]
      processors: [batch]
      exporters: [clickhouse]

    metrics:
      receivers: [kafka]
      processors: [batch]
      exporters: [clickhouse]

  extensions: [zpages, pprof]

  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: "0.0.0.0"
                port: 8888
